local org = {
  OrgTSTimestampActive = {fg = C.yellow},
  OrgTSTimestampInactive = {fg = C.red},
  OrgTSBullet = {fg = C.red},
  OrgTSPropertyDrawer = {fg = C.red, style = "bold,reverse"},
  OrgTSDrawer = {fg = C.red},
  OrgTSTag = {fg = C.red},
  OrgTSPlan = {fg = C.red},
  OrgTSComment = {fg = C.red},
  OrgTSDirective = {fg = C.red},
  OrgTSCheckbox = {fg = C.red},
  OrgTSCheckboxChecked = {fg = C.red},
  OrgTSCheckboxHalfChecked = {fg = C.red},
  OrgTSCheckboxUnchecked = {fg = C.red},
  OrgTSHeadlineLevel1 = {fg = C.cyan, style = "bold"},
  OrgTSHeadlineLevel2 = {fg = C.magenta, style = "bold"},
  OrgTSHeadlineLevel3 = {fg = C.purple, style = "bold"},
  NeorgHeading1 = {fg = C.cyan, style = "bold"},
  NeorgHeading2 = {fg = C.magenta, style = "bold"},
  NeorgHeading3 = {fg = C.purple, style = "bold"},
  NeorgHeading1Title = {fg = C.cyan, style = "bold"},
  NeorgHeading2Title = {fg = C.magenta, style = "bold"},
  NeorgHeading3Title = {fg = C.purple, style = "bold"},
  NeorgHeading1Prefix = {fg = C.cyan, style = "bold"},
  NeorgHeading2Prefix = {fg = C.magenta, style = "bold"},
  NeorgHeading3Prefix = {fg = C.purple, style = "bold"},
  OrgTSHeadlineLevel4 = {fg = C.red},
  OrgTSHeadlineLevel5 = {fg = C.red},
  OrgTSHeadlineLevel6 = {fg = C.red},
  OrgTSHeadlineLevel7 = {fg = C.red},
  OrgTSHeadlineLevel8 = {fg = C.red}
}
return org
