local Treesitter = {
  -- TSComment = { fg = C.ui_4 },
  -- TSAnnotation = { fg = C.purple },
  TSAttribute = {fg = C.cyan},
  TSConstructor = {fg = C.blue, style = 'bold'},
  -- TSType = { fg = C.purple },
  -- TSTypeBuiltin = { fg = C.purple },
  TSConditional = {fg = C.magenta, style = 'bold'},
  -- TSException = { fg = C.blue },
  TSInclude = {fg = C.magenta},
  -- TSKeyword = { fg = C.blue },
  TSEnvironment = {fg = C.magenta},
  TSKeywordFunction = {fg = C.blue, style = 'bold'},
  TSLabel = {fg = C.magenta, style = 'bold'},
  TSMath = {fg = C.purple, style = 'bold'},
  -- TSNamespace = { fg = C.blue },
  -- TSRepeat = { fg = C.blue },
  TSConstant = {fg = C.green},
  TSConstBuiltin = {fg = C.green},
  -- TSFloat = { fg = C.red },
  -- TSNumber = { fg = C.red },
  TSBoolean = {fg = C.green},
  -- TSCharacter = { fg = C.green },
  -- TSError = { fg = C.red },
  -- TSFunction = { fg = C.yellow },
  TSFuncBuiltin = {fg = C.blue, style = 'bold'},
  -- TSMethod = { fg = C.yellow },
  -- TSConstMacro = { fg = C.cyan },
  TSFuncMacro = {fg = C.blue, style = 'bold'},
  -- TSVariable = { fg = C.white },
  TSVariableBuiltin = {fg = C.cyan},
  -- TSProperty = { fg = C.cyan },
  -- TSOperator = { fg = C.blue },
  -- TSField = { fg = C.white },
  TSParameter = {fg = C.orange, style = 'italic'},
  -- TSParameterReference = { fg = C.white },
  -- TSSymbol = { fg = C.white },
  -- TSText = { fg = C.fg },
  -- TSPunctDelimiter = { fg = C.ui_4 },
  -- TSTagDelimiter = { fg = C.ui_4 },
  TSPunctBracket = {fg = C.ui_0},
  TSPunctSpecial = {fg = C.orange}
  -- TSString = { fg = C.green },
  -- TSStringRegex = { fg = C.green },
  -- TSStringEscape = { fg = C.green },
  -- TSTag = { fg = C.blue },
  -- TSEmphasis = { style = "italic" },
  -- TSUnderline = { style = "underline" },
  -- TSTitle = { fg = C.blue, style = "bold" },
  -- TSLiteral = { fg = C.green },
  -- TSURI = { fg = C.cyan, style = "underline" },
  -- TSKeywordOperator = { fg = C.blue },
  -- TSStructure = { fg = C.purple},
  -- TSStrong = { fg = C.yellow },
  -- TSQueryLinterError = { fg = C.orange },
}

return Treesitter
